/** \file
 *  This C++ source file was generated by $ANTLR version 3.5.2
 *
 *     -  From the grammar source file : T.g
 *     -                            On : 2015-11-09 15:17:15
 *     -                 for the lexer : TLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram, ElectronDB
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "TLexer.hpp"
/* ----------------------------------------- */



namespace  User  {

/** String literals used by TLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR_UCHAR	lit_1[]  = { 0x3C, 0x3C, 0x65, 0x6C, 0x73, 0x65, 0x3E, 0x3E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_2[]  = { 0x3C, 0x3C, 0x65, 0x6C, 0x73, 0x65, 0x69, 0x66,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_3[]  = { 0x3C, 0x3C, 0x65, 0x6E, 0x64, 0x69, 0x66, 0x3E, 0x3E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_4[]  = { 0x3C, 0x3C, 0x69, 0x66,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_5[]  = { 0x3C, 0x3C, 0x73, 0x65, 0x74,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_6[]  = { 0x3A, 0x3A,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_7[]  = { 0x69, 0x73,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_8[]  = { 0x2B, 0x3D,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_9[]  = { 0x2D, 0x3D,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_10[]  = { 0x5B, 0x5B,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_11[]  = { 0x5D, 0x5D,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_12[]  = { 0x3C, 0x3C,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_13[]  = { 0x3E, 0x3E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_14[]  = { 0x67, 0x74, 0x65,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_15[]  = { 0x73, 0x65, 0x74,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_16[]  = { 0x3C, 0x3C, 0x73, 0x69, 0x6C, 0x65, 0x6E, 0x74, 0x6C, 0x79, 0x3E, 0x3E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_17[]  = { 0x3C, 0x3C, 0x65, 0x6E, 0x64, 0x73, 0x69, 0x6C, 0x65, 0x6E, 0x74, 0x6C, 0x79, 0x3E, 0x3E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_18[]  = { 0x63, 0x68, 0x6F, 0x69, 0x63, 0x65,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_19[]  = { 0x69, 0x66,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_20[]  = { 0x65, 0x6C, 0x73, 0x65, 0x69, 0x66,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_21[]  = { 0x65, 0x6E, 0x64, 0x69, 0x66,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_22[]  = { 0x64, 0x65, 0x6C, 0x61, 0x79,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_23[]  = { 0x61, 0x6E, 0x64,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_24[]  = { 0x6F, 0x72,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_25[]  = { 0x74, 0x72, 0x75, 0x65,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_26[]  = { 0x66, 0x61, 0x6C, 0x73, 0x65,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_27[]  = { 0x2F, 0x2A,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_28[]  = { 0x2A, 0x2F,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_29[]  = { 0x2F, 0x2F,  antlr3::ANTLR_STRING_TERMINATOR};

}


/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

using namespace antlr3;

namespace  User  {

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



TLexer::~TLexer()
{
}

void
TLexer::reset()
{
    this->get_rec()->reset();
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "T.g";

/** \brief Return the name of the grammar file that generated this code.
 */
const char* TLexer::getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called TLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pTLexer initialized for the lex start
 *     - Fail NULL
 */
TLexer::TLexer(StreamType* instream)
:TLexerImplTraits::BaseLexerType(ANTLR_SIZE_HINT, instream, NULL)
{
	// See if we can create a new lexer with the standard constructor
	//
	this->init(instream );
}

/** \brief Create a new lexer called TLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pTLexer initialized for the lex start
 *     - Fail NULL
 */
TLexer::TLexer(StreamType* instream, RecognizerSharedStateType* state)
:TLexerImplTraits::BaseLexerType(ANTLR_SIZE_HINT, instream, state)
{
	this->init(instream );
}

void TLexer::init(StreamType* instream)
{
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in TLexer.h here so you can get a sense
     * of what goes where.
     */

}


/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    163:1: Time : ( Int 's' | Int 'm' );
 */
static const ANTLR_INT32 dfa1_eot[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR_INT32 dfa1_eof[4] =
    {
	-1, -1, -1, -1
    };
static const ANTLR_INT32 dfa1_min[4] =
    {
	48, 48, -1, -1
    };
static const ANTLR_INT32 dfa1_max[4] =
    {
	57, 115, -1, -1
    };
static const ANTLR_INT32 dfa1_accept[4] =
    {
	-1, -1, 1, 2
    };
static const ANTLR_INT32 dfa1_special[4] =
    {
	-1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
static const ANTLR_INT32* dfa1_T_empty	 =   NULL;

static const ANTLR_INT32 dfa1_T0[] =
    {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    };

static const ANTLR_INT32 dfa1_T1[] =
    {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 3, -1, -1, -1, -1, -1, 2
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR_INT32 * const dfa1_transitions[] =
{
    dfa1_T0, dfa1_T1, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 1
 */
class TLexerCyclicDFA1 : public CyclicDFA< TLexerImplTraits, TLexer >, public TLexerTokens
{
public:
	typedef CyclicDFA< TLexerImplTraits, TLexer >  BaseType;
	typedef BaseType::ContextType CtxType;

private:
	

public:
	TLexerCyclicDFA1( ANTLR_INT32	decisionNumber
					, const ANTLR_UCHAR*	description
					, const ANTLR_INT32* const	eot
					, const ANTLR_INT32* const	eof
					, const ANTLR_INT32* const	min
					, const ANTLR_INT32* const	max
					, const ANTLR_INT32* const	accept
					, const ANTLR_INT32* const	special
					, const ANTLR_INT32* const *const	transition)
					:BaseType( decisionNumber, description, eot, eof, min, max, accept,
								special, transition )
	{
		
	}

};

static TLexerCyclicDFA1  cdfa1(
	    1,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const ANTLR_UCHAR*)"163:1: Time : ( Int 's' | Int 'm' );",
	    dfa1_eot,	    /* EOT table			    */
	    dfa1_eof,	    /* EOF table			    */
	    dfa1_min,	    /* Minimum tokens for each state    */
	    dfa1_max,	    /* Maximum tokens for each state    */
	    dfa1_accept,	/* Accept table			    */
	    dfa1_special,	/* Special transition states	    */
	    dfa1_transitions	/* Table of transition tables	    */

	);


/* End of Cyclic DFA 1
 * ---------------------
 *//** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | FuncDec | Equal | Minus | Dollar | Assign | PlusAssign | MinusAssign | DoubleOpenSquareBracket | DoubleCloseSquareBracket | ShiftLeft | ShiftRight | VarName | ThenFunc | Or | Gte | Set | Silently | EndSilently | Choice | ChoiceLeft | If | ElseIf | EndIf | Delay | AndAnd | OrOr | Time | Int | True | False | String | Label | TEXT | COMMENT | LINE_COMMENT | WS );
 */
static const ANTLR_INT32 dfa9_eot[102] =
    {
	-1, 28, -1, -1, 23, 33, 34, -1, -1, -1, -1, 36, 23, 23, 23, 23, 23, 23, 
	23, 46, 23, 23, -1, -1, -1, -1, -1, -1, -1, 55, 57, 58, -1, -1, -1, -1, 
	-1, -1, 23, 23, 23, 23, 23, 23, 23, 66, -1, -1, 23, 23, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 73, 74, 23, 23, 23, 23, 79, -1, 23, 23, -1, -1, -1, 
	-1, -1, -1, 23, 23, 23, 23, -1, 88, 23, -1, -1, 23, 23, 95, 96, -1, 97, 
	-1, -1, -1, 100, 101, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa9_eof[102] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa9_min[102] =
    {
	9, 61, 60, -1, 102, 61, 65, -1, -1, -1, -1, 65, 116, 101, 104, 108, 101, 
	110, 114, 48, 114, 97, -1, -1, -1, 42, -1, -1, -1, 99, 48, 48, -1, -1, 
	-1, -1, -1, -1, 101, 116, 111, 115, 100, 108, 100, 48, -1, -1, 117, 108, 
	-1, -1, 108, -1, 101, -1, -1, -1, -1, 48, 48, 105, 101, 105, 97, 48, -1, 
	101, 115, 115, 100, -1, -1, -1, -1, 99, 105, 102, 121, -1, 48, 101, 101, 
	105, 101, 102, 48, 48, -1, 48, 62, -1, -1, 48, 48, -1, -1, -1, -1, -1, 
	-1, -1
    };
static const ANTLR_INT32 dfa9_max[102] =
    {
	124, 61, 60, -1, 115, 61, 122, -1, -1, -1, -1, 122, 116, 101, 104, 110, 
	101, 110, 114, 115, 114, 97, -1, -1, -1, 47, -1, -1, -1, 115, 122, 122, 
	-1, -1, -1, -1, -1, -1, 101, 116, 111, 115, 100, 108, 100, 122, -1, -1, 
	117, 108, -1, -1, 110, -1, 105, -1, -1, -1, -1, 122, 122, 105, 101, 105, 
	97, 122, -1, 101, 115, 115, 100, -1, -1, -1, -1, 99, 105, 102, 121, -1, 
	122, 101, 101, 115, 101, 102, 122, 122, -1, 122, 105, -1, -1, 122, 122, 
	-1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa9_accept[102] =
    {
	-1, -1, -1, 7, -1, -1, -1, 11, 14, 15, 17, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 37, 38, 39, -1, 42, 12, 1, -1, -1, -1, 13, 9, 10, 18, 20, 
	19, -1, -1, -1, -1, -1, -1, -1, -1, 34, 33, -1, -1, 40, 41, -1, 5, -1, 
	16, 26, 8, 27, -1, -1, -1, -1, -1, -1, -1, 32, -1, -1, -1, -1, 6, 23, 21, 
	22, -1, -1, -1, -1, 31, -1, -1, -1, -1, -1, -1, -1, -1, 35, -1, -1, 4, 
	24, -1, -1, 29, 30, 36, 2, 3, 25, 28
    };
static const ANTLR_INT32 dfa9_special[102] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
static const ANTLR_INT32* dfa9_T_empty	 =   NULL;

static const ANTLR_INT32 dfa9_T0[] =
    {
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, -1, -1, -1, -1, -1, -1, -1, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, -1, -1, -1, -1, 23, -1, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23
    };

static const ANTLR_INT32 dfa9_T1[] =
    {
	65
    };

static const ANTLR_INT32 dfa9_T2[] =
    {
	69, -1, 70
    };

static const ANTLR_INT32 dfa9_T3[] =
    {
	67
    };

static const ANTLR_INT32 dfa9_T4[] =
    {
	31, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 30
    };

static const ANTLR_INT32 dfa9_T5[] =
    {
	29
    };

static const ANTLR_INT32 dfa9_T6[] =
    {
	94
    };

static const ANTLR_INT32 dfa9_T7[] =
    {
	85
    };

static const ANTLR_INT32 dfa9_T8[] =
    {
	76
    };

static const ANTLR_INT32 dfa9_T9[] =
    {
	62
    };

static const ANTLR_INT32 dfa9_T10[] =
    {
	78
    };

static const ANTLR_INT32 dfa9_T11[] =
    {
	87
    };

static const ANTLR_INT32 dfa9_T12[] =
    {
	64
    };

static const ANTLR_INT32 dfa9_T13[] =
    {
	50, -1, -1, -1, -1, 51
    };

static const ANTLR_INT32 dfa9_T14[] =
    {
	77
    };

static const ANTLR_INT32 dfa9_T15[] =
    {
	86
    };

static const ANTLR_INT32 dfa9_T16[] =
    {
	63
    };

static const ANTLR_INT32 dfa9_T17[] =
    {
	19, 19, 19, 19, 19, 19, 19, 19, 19, 19, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, 47, -1, -1, -1, -1, -1, 47
    };

static const ANTLR_INT32 dfa9_T18[] =
    {
	89
    };

static const ANTLR_INT32 dfa9_T19[] =
    {
	48
    };

static const ANTLR_INT32 dfa9_T20[] =
    {
	37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 
	37, 37, 37, 37, 37, 37, 37, 37, -1, -1, -1, -1, 37, -1, 37, 37, 37, 37, 
	37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 
	37, 37, 37, 37
    };

static const ANTLR_INT32 dfa9_T21[] =
    {
	80
    };

static const ANTLR_INT32 dfa9_T22[] =
    {
	49
    };

static const ANTLR_INT32 dfa9_T23[] =
    {
	81
    };

static const ANTLR_INT32 dfa9_T24[] =
    {
	68
    };

static const ANTLR_INT32 dfa9_T25[] =
    {
	32
    };

static const ANTLR_INT32 dfa9_T26[] =
    {
	83
    };

static const ANTLR_INT32 dfa9_T27[] =
    {
	71, -1, -1, -1, 72
    };

static const ANTLR_INT32 dfa9_T28[] =
    {
	91, -1, -1, -1, -1, -1, -1, -1, -1, -1, 92
    };

static const ANTLR_INT32 dfa9_T29[] =
    {
	26, 26, -1, 26, 26, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 26, -1, 22, 24, 6, -1, -1, -1, -1, -1, -1, 1, -1, 5, 
	-1, 25, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 3, -1, 2, 7, 10, -1, -1, 
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
	23, 23, 23, 23, 23, 23, 23, 23, 8, -1, 9, -1, 23, -1, 17, 23, 14, 16, 15, 
	21, 12, 23, 4, 23, 23, 23, 23, 23, 18, 23, 23, 23, 13, 20, 23, 23, 23, 
	23, 23, 23, -1, 11
    };

static const ANTLR_INT32 dfa9_T30[] =
    {
	45
    };

static const ANTLR_INT32 dfa9_T31[] =
    {
	44
    };

static const ANTLR_INT32 dfa9_T32[] =
    {
	43
    };

static const ANTLR_INT32 dfa9_T33[] =
    {
	41, -1, 42
    };

static const ANTLR_INT32 dfa9_T34[] =
    {
	40
    };

static const ANTLR_INT32 dfa9_T35[] =
    {
	98, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, 99
    };

static const ANTLR_INT32 dfa9_T36[] =
    {
	82
    };

static const ANTLR_INT32 dfa9_T37[] =
    {
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, -1, -1, -1, -1, 35, -1, 35, 35, 35, 35, 
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
	35, 35, 35, 35
    };

static const ANTLR_INT32 dfa9_T38[] =
    {
	90
    };

static const ANTLR_INT32 dfa9_T39[] =
    {
	75
    };

static const ANTLR_INT32 dfa9_T40[] =
    {
	61
    };

static const ANTLR_INT32 dfa9_T41[] =
    {
	93
    };

static const ANTLR_INT32 dfa9_T42[] =
    {
	84
    };

static const ANTLR_INT32 dfa9_T43[] =
    {
	39
    };

static const ANTLR_INT32 dfa9_T44[] =
    {
	38
    };

static const ANTLR_INT32 dfa9_T45[] =
    {
	59
    };

static const ANTLR_INT32 dfa9_T46[] =
    {
	27
    };

static const ANTLR_INT32 dfa9_T47[] =
    {
	60
    };

static const ANTLR_INT32 dfa9_T48[] =
    {
	56, -1, 52, -1, -1, -1, 53, -1, -1, -1, -1, -1, -1, -1, -1, -1, 54
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR_INT32 * const dfa9_transitions[] =
{
    dfa9_T29, dfa9_T46, dfa9_T5, NULL, dfa9_T4, dfa9_T25, dfa9_T37, NULL, 
    NULL, NULL, NULL, dfa9_T20, dfa9_T44, dfa9_T43, dfa9_T34, dfa9_T33, 
    dfa9_T32, dfa9_T31, dfa9_T30, dfa9_T17, dfa9_T19, dfa9_T22, NULL, NULL, 
    NULL, dfa9_T13, NULL, NULL, NULL, dfa9_T48, dfa9_T0, dfa9_T0, NULL, 
    NULL, NULL, NULL, NULL, NULL, dfa9_T45, dfa9_T47, dfa9_T40, dfa9_T9, 
    dfa9_T16, dfa9_T12, dfa9_T1, dfa9_T0, NULL, NULL, dfa9_T3, dfa9_T24, 
    NULL, NULL, dfa9_T2, NULL, dfa9_T27, NULL, NULL, NULL, NULL, dfa9_T0, 
    dfa9_T0, dfa9_T39, dfa9_T8, dfa9_T14, dfa9_T10, dfa9_T0, NULL, dfa9_T21, 
    dfa9_T23, dfa9_T36, dfa9_T26, NULL, NULL, NULL, NULL, dfa9_T42, dfa9_T7, 
    dfa9_T15, dfa9_T11, NULL, dfa9_T0, dfa9_T18, dfa9_T38, dfa9_T28, dfa9_T41, 
    dfa9_T6, dfa9_T0, dfa9_T0, NULL, dfa9_T0, dfa9_T35, NULL, NULL, dfa9_T0, 
    dfa9_T0, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 9
 */
class TLexerCyclicDFA9 : public CyclicDFA< TLexerImplTraits, TLexer >, public TLexerTokens
{
public:
	typedef CyclicDFA< TLexerImplTraits, TLexer >  BaseType;
	typedef BaseType::ContextType CtxType;

private:
	

public:
	TLexerCyclicDFA9( ANTLR_INT32	decisionNumber
					, const ANTLR_UCHAR*	description
					, const ANTLR_INT32* const	eot
					, const ANTLR_INT32* const	eof
					, const ANTLR_INT32* const	min
					, const ANTLR_INT32* const	max
					, const ANTLR_INT32* const	accept
					, const ANTLR_INT32* const	special
					, const ANTLR_INT32* const *const	transition)
					:BaseType( decisionNumber, description, eot, eof, min, max, accept,
								special, transition )
	{
		
	}

};

static TLexerCyclicDFA9  cdfa9(
	    9,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const ANTLR_UCHAR*)"1:1: Tokens : ( T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | FuncDec | Equal | Minus | Dollar | Assign | PlusAssign | MinusAssign | DoubleOpenSquareBracket | DoubleCloseSquareBracket | ShiftLeft | ShiftRight | VarName | ThenFunc | Or | Gte | Set | Silently | EndSilently | Choice | ChoiceLeft | If | ElseIf | EndIf | Delay | AndAnd | OrOr | Time | Int | True | False | String | Label | TEXT | COMMENT | LINE_COMMENT | WS );",
	    dfa9_eot,	    /* EOT table			    */
	    dfa9_eof,	    /* EOF table			    */
	    dfa9_min,	    /* Minimum tokens for each state    */
	    dfa9_max,	    /* Maximum tokens for each state    */
	    dfa9_accept,	/* Accept table			    */
	    dfa9_special,	/* Special transition states	    */
	    dfa9_transitions	/* Table of transition tables	    */

	);


/* End of Cyclic DFA 9
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 32:7: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__40()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__40;


    // T.g:32:7: ( '+' )
    // T.g:32:9: '+'
    {
         this->matchc('+');
        if  (this->hasException())
        {
            goto ruleT__40Ex;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 33:7: ( '<<else>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__41()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__41;


    // T.g:33:7: ( '<<else>>' )
    // T.g:33:9: '<<else>>'
    {
        this->matchs(lit_1);
        if  (this->hasException())
        {
            goto ruleT__41Ex;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 34:7: ( '<<elseif' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__42()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__42;


    // T.g:34:7: ( '<<elseif' )
    // T.g:34:9: '<<elseif'
    {
        this->matchs(lit_2);
        if  (this->hasException())
        {
            goto ruleT__42Ex;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 35:7: ( '<<endif>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__43()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__43;


    // T.g:35:7: ( '<<endif>>' )
    // T.g:35:9: '<<endif>>'
    {
        this->matchs(lit_3);
        if  (this->hasException())
        {
            goto ruleT__43Ex;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 36:7: ( '<<if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__44()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__44;


    // T.g:36:7: ( '<<if' )
    // T.g:36:9: '<<if'
    {
        this->matchs(lit_4);
        if  (this->hasException())
        {
            goto ruleT__44Ex;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 37:7: ( '<<set' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mT__45()
{
    ANTLR_UINT32	_type;
      

    _type	    = T__45;


    // T.g:37:7: ( '<<set' )
    // T.g:37:9: '<<set'
    {
        this->matchs(lit_5);
        if  (this->hasException())
        {
            goto ruleT__45Ex;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 112:9: ( '::' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FuncDec
 *
 * Looks to match the characters the constitute the token FuncDec
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mFuncDec()
{
    ANTLR_UINT32	_type;
      

    _type	    = FuncDec;


    // T.g:112:9: ( '::' )
    // T.g:112:11: '::'
    {
        this->matchs(lit_6);
        if  (this->hasException())
        {
            goto ruleFuncDecEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleFuncDecEx; /* Prevent compiler warnings */
    ruleFuncDecEx: ;

}
// $ANTLR end FuncDec

//   Comes from: 114:7: ( 'is' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Equal
 *
 * Looks to match the characters the constitute the token Equal
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mEqual()
{
    ANTLR_UINT32	_type;
      

    _type	    = Equal;


    // T.g:114:7: ( 'is' )
    // T.g:114:9: 'is'
    {
        this->matchs(lit_7);
        if  (this->hasException())
        {
            goto ruleEqualEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleEqualEx; /* Prevent compiler warnings */
    ruleEqualEx: ;

}
// $ANTLR end Equal

//   Comes from: 116:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Minus
 *
 * Looks to match the characters the constitute the token Minus
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mMinus()
{
    ANTLR_UINT32	_type;
      

    _type	    = Minus;


    // T.g:116:7: ( '-' )
    // T.g:116:9: '-'
    {
         this->matchc('-');
        if  (this->hasException())
        {
            goto ruleMinusEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMinusEx; /* Prevent compiler warnings */
    ruleMinusEx: ;

}
// $ANTLR end Minus

//   Comes from: 118:8: ( '$' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Dollar
 *
 * Looks to match the characters the constitute the token Dollar
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mDollar()
{
    ANTLR_UINT32	_type;
      

    _type	    = Dollar;


    // T.g:118:8: ( '$' )
    // T.g:118:10: '$'
    {
         this->matchc('$');
        if  (this->hasException())
        {
            goto ruleDollarEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDollarEx; /* Prevent compiler warnings */
    ruleDollarEx: ;

}
// $ANTLR end Dollar

//   Comes from: 120:8: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Assign
 *
 * Looks to match the characters the constitute the token Assign
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mAssign()
{
    ANTLR_UINT32	_type;
      

    _type	    = Assign;


    // T.g:120:8: ( '=' )
    // T.g:120:10: '='
    {
         this->matchc('=');
        if  (this->hasException())
        {
            goto ruleAssignEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleAssignEx; /* Prevent compiler warnings */
    ruleAssignEx: ;

}
// $ANTLR end Assign

//   Comes from: 121:12: ( '+=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PlusAssign
 *
 * Looks to match the characters the constitute the token PlusAssign
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mPlusAssign()
{
    ANTLR_UINT32	_type;
      

    _type	    = PlusAssign;


    // T.g:121:12: ( '+=' )
    // T.g:121:14: '+='
    {
        this->matchs(lit_8);
        if  (this->hasException())
        {
            goto rulePlusAssignEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto rulePlusAssignEx; /* Prevent compiler warnings */
    rulePlusAssignEx: ;

}
// $ANTLR end PlusAssign

//   Comes from: 122:13: ( '-=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MinusAssign
 *
 * Looks to match the characters the constitute the token MinusAssign
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mMinusAssign()
{
    ANTLR_UINT32	_type;
      

    _type	    = MinusAssign;


    // T.g:122:13: ( '-=' )
    // T.g:122:15: '-='
    {
        this->matchs(lit_9);
        if  (this->hasException())
        {
            goto ruleMinusAssignEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMinusAssignEx; /* Prevent compiler warnings */
    ruleMinusAssignEx: ;

}
// $ANTLR end MinusAssign

//   Comes from: 124:24: ( '[[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DoubleOpenSquareBracket
 *
 * Looks to match the characters the constitute the token DoubleOpenSquareBracket
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mDoubleOpenSquareBracket()
{
    ANTLR_UINT32	_type;
      

    _type	    = DoubleOpenSquareBracket;


    // T.g:124:24: ( '[[' )
    // T.g:124:26: '[['
    {
        this->matchs(lit_10);
        if  (this->hasException())
        {
            goto ruleDoubleOpenSquareBracketEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDoubleOpenSquareBracketEx; /* Prevent compiler warnings */
    ruleDoubleOpenSquareBracketEx: ;

}
// $ANTLR end DoubleOpenSquareBracket

//   Comes from: 125:25: ( ']]' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DoubleCloseSquareBracket
 *
 * Looks to match the characters the constitute the token DoubleCloseSquareBracket
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mDoubleCloseSquareBracket()
{
    ANTLR_UINT32	_type;
      

    _type	    = DoubleCloseSquareBracket;


    // T.g:125:25: ( ']]' )
    // T.g:125:27: ']]'
    {
        this->matchs(lit_11);
        if  (this->hasException())
        {
            goto ruleDoubleCloseSquareBracketEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDoubleCloseSquareBracketEx; /* Prevent compiler warnings */
    ruleDoubleCloseSquareBracketEx: ;

}
// $ANTLR end DoubleCloseSquareBracket

//   Comes from: 127:10: ( '<<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ShiftLeft
 *
 * Looks to match the characters the constitute the token ShiftLeft
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mShiftLeft()
{
    ANTLR_UINT32	_type;
      

    _type	    = ShiftLeft;


    // T.g:127:10: ( '<<' )
    // T.g:127:21: '<<'
    {
        this->matchs(lit_12);
        if  (this->hasException())
        {
            goto ruleShiftLeftEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleShiftLeftEx; /* Prevent compiler warnings */
    ruleShiftLeftEx: ;

}
// $ANTLR end ShiftLeft

//   Comes from: 129:11: ( '>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ShiftRight
 *
 * Looks to match the characters the constitute the token ShiftRight
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mShiftRight()
{
    ANTLR_UINT32	_type;
      

    _type	    = ShiftRight;


    // T.g:129:11: ( '>>' )
    // T.g:129:21: '>>'
    {
        this->matchs(lit_13);
        if  (this->hasException())
        {
            goto ruleShiftRightEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleShiftRightEx; /* Prevent compiler warnings */
    ruleShiftRightEx: ;

}
// $ANTLR end ShiftRight

//   Comes from: 132:8: ( '$' Label )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VarName
 *
 * Looks to match the characters the constitute the token VarName
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mVarName()
{
    ANTLR_UINT32	_type;
      

    _type	    = VarName;


    // T.g:132:8: ( '$' Label )
    // T.g:132:10: '$' Label
    {
         this->matchc('$');
        if  (this->hasException())
        {
            goto ruleVarNameEx;
        }


        /* 132:10: '$' Label */
        mLabel();
        if  (this->hasException())
        {
            goto ruleVarNameEx;
        }



    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleVarNameEx; /* Prevent compiler warnings */
    ruleVarNameEx: ;

}
// $ANTLR end VarName

//   Comes from: 134:9: ( Or Label )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ThenFunc
 *
 * Looks to match the characters the constitute the token ThenFunc
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mThenFunc()
{
    ANTLR_UINT32	_type;
      

    _type	    = ThenFunc;


    // T.g:134:9: ( Or Label )
    // T.g:134:11: Or Label
    {
        /* 134:11: Or Label */
        mOr();
        if  (this->hasException())
        {
            goto ruleThenFuncEx;
        }



        /* 134:11: Or Label */
        mLabel();
        if  (this->hasException())
        {
            goto ruleThenFuncEx;
        }



    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleThenFuncEx; /* Prevent compiler warnings */
    ruleThenFuncEx: ;

}
// $ANTLR end ThenFunc

//   Comes from: 136:4: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Or
 *
 * Looks to match the characters the constitute the token Or
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mOr()
{
    ANTLR_UINT32	_type;
      

    _type	    = Or;


    // T.g:136:4: ( '|' )
    // T.g:136:6: '|'
    {
         this->matchc('|');
        if  (this->hasException())
        {
            goto ruleOrEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleOrEx; /* Prevent compiler warnings */
    ruleOrEx: ;

}
// $ANTLR end Or

//   Comes from: 138:5: ( 'gte' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Gte
 *
 * Looks to match the characters the constitute the token Gte
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mGte()
{
    ANTLR_UINT32	_type;
      

    _type	    = Gte;


    // T.g:138:5: ( 'gte' )
    // T.g:138:7: 'gte'
    {
        this->matchs(lit_14);
        if  (this->hasException())
        {
            goto ruleGteEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleGteEx; /* Prevent compiler warnings */
    ruleGteEx: ;

}
// $ANTLR end Gte

//   Comes from: 140:5: ( 'set' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Set
 *
 * Looks to match the characters the constitute the token Set
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mSet()
{
    ANTLR_UINT32	_type;
      

    _type	    = Set;


    // T.g:140:5: ( 'set' )
    // T.g:140:7: 'set'
    {
        this->matchs(lit_15);
        if  (this->hasException())
        {
            goto ruleSetEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleSetEx; /* Prevent compiler warnings */
    ruleSetEx: ;

}
// $ANTLR end Set

//   Comes from: 143:10: ( '<<silently>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Silently
 *
 * Looks to match the characters the constitute the token Silently
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mSilently()
{
    ANTLR_UINT32	_type;
      

    _type	    = Silently;


    // T.g:143:10: ( '<<silently>>' )
    // T.g:143:12: '<<silently>>'
    {
        this->matchs(lit_16);
        if  (this->hasException())
        {
            goto ruleSilentlyEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleSilentlyEx; /* Prevent compiler warnings */
    ruleSilentlyEx: ;

}
// $ANTLR end Silently

//   Comes from: 144:12: ( '<<endsilently>>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EndSilently
 *
 * Looks to match the characters the constitute the token EndSilently
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mEndSilently()
{
    ANTLR_UINT32	_type;
      

    _type	    = EndSilently;


    // T.g:144:12: ( '<<endsilently>>' )
    // T.g:144:14: '<<endsilently>>'
    {
        this->matchs(lit_17);
        if  (this->hasException())
        {
            goto ruleEndSilentlyEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleEndSilentlyEx; /* Prevent compiler warnings */
    ruleEndSilentlyEx: ;

}
// $ANTLR end EndSilently

//   Comes from: 146:8: ( 'choice' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Choice
 *
 * Looks to match the characters the constitute the token Choice
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mChoice()
{
    ANTLR_UINT32	_type;
      

    _type	    = Choice;


    // T.g:146:8: ( 'choice' )
    // T.g:146:10: 'choice'
    {
        this->matchs(lit_18);
        if  (this->hasException())
        {
            goto ruleChoiceEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleChoiceEx; /* Prevent compiler warnings */
    ruleChoiceEx: ;

}
// $ANTLR end Choice

//   Comes from: 148:12: ( ShiftLeft Choice )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ChoiceLeft
 *
 * Looks to match the characters the constitute the token ChoiceLeft
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mChoiceLeft()
{
    ANTLR_UINT32	_type;
      

    _type	    = ChoiceLeft;


    // T.g:148:12: ( ShiftLeft Choice )
    // T.g:148:14: ShiftLeft Choice
    {
        /* 148:14: ShiftLeft Choice */
        mShiftLeft();
        if  (this->hasException())
        {
            goto ruleChoiceLeftEx;
        }



        /* 148:14: ShiftLeft Choice */
        mChoice();
        if  (this->hasException())
        {
            goto ruleChoiceLeftEx;
        }



    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleChoiceLeftEx; /* Prevent compiler warnings */
    ruleChoiceLeftEx: ;

}
// $ANTLR end ChoiceLeft

//   Comes from: 150:4: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start If
 *
 * Looks to match the characters the constitute the token If
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mIf()
{
    ANTLR_UINT32	_type;
      

    _type	    = If;


    // T.g:150:4: ( 'if' )
    // T.g:150:6: 'if'
    {
        this->matchs(lit_19);
        if  (this->hasException())
        {
            goto ruleIfEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleIfEx; /* Prevent compiler warnings */
    ruleIfEx: ;

}
// $ANTLR end If

//   Comes from: 152:8: ( 'elseif' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ElseIf
 *
 * Looks to match the characters the constitute the token ElseIf
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mElseIf()
{
    ANTLR_UINT32	_type;
      

    _type	    = ElseIf;


    // T.g:152:8: ( 'elseif' )
    // T.g:152:10: 'elseif'
    {
        this->matchs(lit_20);
        if  (this->hasException())
        {
            goto ruleElseIfEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleElseIfEx; /* Prevent compiler warnings */
    ruleElseIfEx: ;

}
// $ANTLR end ElseIf

//   Comes from: 154:7: ( 'endif' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EndIf
 *
 * Looks to match the characters the constitute the token EndIf
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mEndIf()
{
    ANTLR_UINT32	_type;
      

    _type	    = EndIf;


    // T.g:154:7: ( 'endif' )
    // T.g:154:9: 'endif'
    {
        this->matchs(lit_21);
        if  (this->hasException())
        {
            goto ruleEndIfEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleEndIfEx; /* Prevent compiler warnings */
    ruleEndIfEx: ;

}
// $ANTLR end EndIf

//   Comes from: 156:7: ( 'delay' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Delay
 *
 * Looks to match the characters the constitute the token Delay
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mDelay()
{
    ANTLR_UINT32	_type;
      

    _type	    = Delay;


    // T.g:156:7: ( 'delay' )
    // T.g:156:9: 'delay'
    {
        this->matchs(lit_22);
        if  (this->hasException())
        {
            goto ruleDelayEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDelayEx; /* Prevent compiler warnings */
    ruleDelayEx: ;

}
// $ANTLR end Delay

//   Comes from: 158:8: ( 'and' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start AndAnd
 *
 * Looks to match the characters the constitute the token AndAnd
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mAndAnd()
{
    ANTLR_UINT32	_type;
      

    _type	    = AndAnd;


    // T.g:158:8: ( 'and' )
    // T.g:158:10: 'and'
    {
        this->matchs(lit_23);
        if  (this->hasException())
        {
            goto ruleAndAndEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleAndAndEx; /* Prevent compiler warnings */
    ruleAndAndEx: ;

}
// $ANTLR end AndAnd

//   Comes from: 160:6: ( 'or' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OrOr
 *
 * Looks to match the characters the constitute the token OrOr
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mOrOr()
{
    ANTLR_UINT32	_type;
      

    _type	    = OrOr;


    // T.g:160:6: ( 'or' )
    // T.g:160:8: 'or'
    {
        this->matchs(lit_24);
        if  (this->hasException())
        {
            goto ruleOrOrEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleOrOrEx; /* Prevent compiler warnings */
    ruleOrOrEx: ;

}
// $ANTLR end OrOr

//   Comes from: 163:6: ( Int 's' | Int 'm' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Time
 *
 * Looks to match the characters the constitute the token Time
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mTime()
{
    ANTLR_UINT32	_type;
      

    _type	    = Time;


    {
        //  T.g:163:6: ( Int 's' | Int 'm' )

        ANTLR_UINT32 alt1;

        alt1=2;

        alt1 = cdfa1.predict(this, this->get_rec(), this->get_istream(), cdfa1 );
        if  (this->hasException())
        {
            goto ruleTimeEx;
        }

        switch (alt1)
        {
    	case 1:
    	    // T.g:163:8: Int 's'
    	    {
    	        /* 163:8: Int 's' */
    	        mInt();
    	        if  (this->hasException())
    	        {
    	            goto ruleTimeEx;
    	        }



    	         this->matchc('s');
    	        if  (this->hasException())
    	        {
    	            goto ruleTimeEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // T.g:163:17: Int 'm'
    	    {
    	        /* 163:17: Int 'm' */
    	        mInt();
    	        if  (this->hasException())
    	        {
    	            goto ruleTimeEx;
    	        }



    	         this->matchc('m');
    	        if  (this->hasException())
    	        {
    	            goto ruleTimeEx;
    	        }


    	    }
    	    break;

        }
    }
	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleTimeEx; /* Prevent compiler warnings */
    ruleTimeEx: ;

}
// $ANTLR end Time

//   Comes from: 165:5: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Int
 *
 * Looks to match the characters the constitute the token Int
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mInt()
{
    ANTLR_UINT32	_type;
      

    _type	    = Int;


    // T.g:165:5: ( ( '0' .. '9' )+ )
    // T.g:165:7: ( '0' .. '9' )+
    {
        // T.g:165:7: ( '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( this->LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2)
        	{
        	    case 1:
        	        // T.g:
        	        {
        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
        	            {
        	                this->consume();
        	            }
        	            else
        	            {
        	                new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	                this->recover();
        	                goto ruleIntEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		new ANTLR_Exception< TLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


        		goto ruleIntEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleIntEx; /* Prevent compiler warnings */
    ruleIntEx: ;

}
// $ANTLR end Int

//   Comes from: 167:6: ( 'true' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start True
 *
 * Looks to match the characters the constitute the token True
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mTrue()
{
    ANTLR_UINT32	_type;
      

    _type	    = True;


    // T.g:167:6: ( 'true' )
    // T.g:167:8: 'true'
    {
        this->matchs(lit_25);
        if  (this->hasException())
        {
            goto ruleTrueEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleTrueEx; /* Prevent compiler warnings */
    ruleTrueEx: ;

}
// $ANTLR end True

//   Comes from: 169:7: ( 'false' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start False
 *
 * Looks to match the characters the constitute the token False
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mFalse()
{
    ANTLR_UINT32	_type;
      

    _type	    = False;


    // T.g:169:7: ( 'false' )
    // T.g:169:9: 'false'
    {
        this->matchs(lit_26);
        if  (this->hasException())
        {
            goto ruleFalseEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleFalseEx; /* Prevent compiler warnings */
    ruleFalseEx: ;

}
// $ANTLR end False

//   Comes from: 171:7: ( '\"' (~ ( '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start String
 *
 * Looks to match the characters the constitute the token String
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mString()
{
    ANTLR_UINT32	_type;
      

    _type	    = String;


    // T.g:171:7: ( '\"' (~ ( '\"' ) )* '\"' )
    // T.g:171:9: '\"' (~ ( '\"' ) )* '\"'
    {
         this->matchc('"');
        if  (this->hasException())
        {
            goto ruleStringEx;
        }


        // T.g:171:13: (~ ( '\"' ) )*

        for (;;)
        {
            int alt3=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = this->LA(1);
                if ( (((LA3_0 >= 0x0000) && (LA3_0 <= '!')) || ((LA3_0 >= '#') && (LA3_0 <= 0xFFFF))))
                {
                    alt3=1;
                }

            }
            switch (alt3)
            {
        	case 1:
        	    // T.g:
        	    {
        	        if ( ((this->LA(1) >= 0x0000) && (this->LA(1) <= '!')) || ((this->LA(1) >= '#') && (this->LA(1) <= 0xFFFF)) )
        	        {
        	            this->consume();
        	        }
        	        else
        	        {
        	            new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	            this->recover();
        	            goto ruleStringEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


         this->matchc('"');
        if  (this->hasException())
        {
            goto ruleStringEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleStringEx; /* Prevent compiler warnings */
    ruleStringEx: ;

}
// $ANTLR end String

//   Comes from: 173:6: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start Label
 *
 * Looks to match the characters the constitute the token Label
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mLabel()
{
    ANTLR_UINT32	_type;
      

    _type	    = Label;


    // T.g:173:6: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // T.g:173:8: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((this->LA(1) >= 'A') && (this->LA(1) <= 'Z')) || this->LA(1) == '_' || ((this->LA(1) >= 'a') && (this->LA(1) <= 'z')) )
        {
            this->consume();
        }
        else
        {
            new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

            this->recover();
            goto ruleLabelEx;
        }


        // T.g:173:39: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt4=2;
            switch ( this->LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt4=1;
            	}
                break;

            }

            switch (alt4)
            {
        	case 1:
        	    // T.g:
        	    {
        	        if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) || ((this->LA(1) >= 'A') && (this->LA(1) <= 'Z')) || this->LA(1) == '_' || ((this->LA(1) >= 'a') && (this->LA(1) <= 'z')) )
        	        {
        	            this->consume();
        	        }
        	        else
        	        {
        	            new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	            this->recover();
        	            goto ruleLabelEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleLabelEx; /* Prevent compiler warnings */
    ruleLabelEx: ;

}
// $ANTLR end Label

//   Comes from: 175:5: ( '#' (~ ( '#' ) )+ '#' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TEXT
 *
 * Looks to match the characters the constitute the token TEXT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mTEXT()
{
    ANTLR_UINT32	_type;
      

    _type	    = TEXT;


    // T.g:175:5: ( '#' (~ ( '#' ) )+ '#' )
    // T.g:175:7: '#' (~ ( '#' ) )+ '#'
    {
         this->matchc('#');
        if  (this->hasException())
        {
            goto ruleTEXTEx;
        }


        // T.g:175:11: (~ ( '#' ) )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	{
        	   /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
        	    */
        	    int LA5_0 = this->LA(1);
        	    if ( (((LA5_0 >= 0x0000) && (LA5_0 <= '"')) || ((LA5_0 >= '$') && (LA5_0 <= 0xFFFF))))
        	    {
        	        alt5=1;
        	    }

        	}
        	switch (alt5)
        	{
        	    case 1:
        	        // T.g:
        	        {
        	            if ( ((this->LA(1) >= 0x0000) && (this->LA(1) <= '"')) || ((this->LA(1) >= '$') && (this->LA(1) <= 0xFFFF)) )
        	            {
        	                this->consume();
        	            }
        	            else
        	            {
        	                new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	                this->recover();
        	                goto ruleTEXTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		new ANTLR_Exception< TLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


        		goto ruleTEXTEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

         this->matchc('#');
        if  (this->hasException())
        {
            goto ruleTEXTEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleTEXTEx; /* Prevent compiler warnings */
    ruleTEXTEx: ;

}
// $ANTLR end TEXT

//   Comes from: 178:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mCOMMENT()
{
    ANTLR_UINT32	_type;
      

    _type	    = COMMENT;


    // T.g:178:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
    // T.g:178:7: '/*' ( options {greedy=false; } : . )* '*/'
    {
        this->matchs(lit_27);
        if  (this->hasException())
        {
            goto ruleCOMMENTEx;
        }




        // T.g:178:12: ( options {greedy=false; } : . )*

        for (;;)
        {
            int alt6=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA6_0 = this->LA(1);
                if ( (LA6_0 == '*'))
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA6_1 = this->LA(2);
                        if ( (LA6_1 == '/'))
                        {
                            alt6=2;
                        }
                        else if ( (((LA6_1 >= 0x0000) && (LA6_1 <= '.')) || ((LA6_1 >= '0') && (LA6_1 <= 0xFFFF))))
                        {
                            alt6=1;
                        }

                    }
                }
                else if ( (((LA6_0 >= 0x0000) && (LA6_0 <= ')')) || ((LA6_0 >= '+') && (LA6_0 <= 0xFFFF))))
                {
                    alt6=1;
                }

            }
            switch (alt6)
            {
        	case 1:
        	    // T.g:178:40: .
        	    {
        	        this->matchAny();
        	        if  (this->hasException())
        	        {
        	            goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop6;	/* break out of the loop */
        	    break;
            }
        }
        loop6: ; /* Jump out to here if this rule does not match */


        this->matchs(lit_28);
        if  (this->hasException())
        {
            goto ruleCOMMENTEx;
        }




        {
            this->get_state()->get_channel()=HIDDEN;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 181:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LINE_COMMENT
 *
 * Looks to match the characters the constitute the token LINE_COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mLINE_COMMENT()
{
    ANTLR_UINT32	_type;
      

    _type	    = LINE_COMMENT;


    // T.g:181:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
    // T.g:181:7: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
    {
        this->matchs(lit_29);
        if  (this->hasException())
        {
            goto ruleLINE_COMMENTEx;
        }




        // T.g:181:12: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt7=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA7_0 = this->LA(1);
                if ( (((LA7_0 >= 0x0000) && (LA7_0 <= '\t')) || ((LA7_0 >= 0x000B) && (LA7_0 <= '\f')) || ((LA7_0 >= 0x000E) && (LA7_0 <= 0xFFFF))))
                {
                    alt7=1;
                }

            }
            switch (alt7)
            {
        	case 1:
        	    // T.g:
        	    {
        	        if ( ((this->LA(1) >= 0x0000) && (this->LA(1) <= '\t')) || ((this->LA(1) >= 0x000B) && (this->LA(1) <= '\f')) || ((this->LA(1) >= 0x000E) && (this->LA(1) <= 0xFFFF)) )
        	        {
        	            this->consume();
        	        }
        	        else
        	        {
        	            new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	            this->recover();
        	            goto ruleLINE_COMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop7;	/* break out of the loop */
        	    break;
            }
        }
        loop7: ; /* Jump out to here if this rule does not match */


        // T.g:181:26: ( '\\r' )?
        {
            int alt8=2;
            switch ( this->LA(1) )
            {
                case '\r':
                	{
                		alt8=1;
                	}
                    break;
            }

            switch (alt8)
            {
        	case 1:
        	    // T.g:181:26: '\\r'
        	    {
        	         this->matchc('\r');
        	        if  (this->hasException())
        	        {
        	            goto ruleLINE_COMMENTEx;
        	        }


        	    }
        	    break;

            }
        }

         this->matchc('\n');
        if  (this->hasException())
        {
            goto ruleLINE_COMMENTEx;
        }


        {
            this->get_state()->get_channel()=HIDDEN;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleLINE_COMMENTEx; /* Prevent compiler warnings */
    ruleLINE_COMMENTEx: ;

}
// $ANTLR end LINE_COMMENT

//   Comes from: 183:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void TLexer::mWS()
{
    ANTLR_UINT32	_type;
      

    _type	    = WS;


    // T.g:183:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
    // T.g:183:7: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
    {
        if ( ((this->LA(1) >= '\t') && (this->LA(1) <= '\n')) || ((this->LA(1) >= '\f') && (this->LA(1) <= '\r')) || this->LA(1) == ' ' )
        {
            this->consume();
        }
        else
        {
            new ANTLR_Exception< TLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

            this->recover();
            goto ruleWSEx;
        }


        {
            this->get_state()->get_channel()=HIDDEN;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
void
TLexer::mTokens()
{
    {
        //  T.g:1:8: ( T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | FuncDec | Equal | Minus | Dollar | Assign | PlusAssign | MinusAssign | DoubleOpenSquareBracket | DoubleCloseSquareBracket | ShiftLeft | ShiftRight | VarName | ThenFunc | Or | Gte | Set | Silently | EndSilently | Choice | ChoiceLeft | If | ElseIf | EndIf | Delay | AndAnd | OrOr | Time | Int | True | False | String | Label | TEXT | COMMENT | LINE_COMMENT | WS )

        ANTLR_UINT32 alt9;

        alt9=42;

        alt9 = cdfa9.predict(this, this->get_rec(), this->get_istream(), cdfa9 );
        if  (this->hasException())
        {
            goto ruleTokensEx;
        }

        switch (alt9)
        {
    	case 1:
    	    // T.g:1:10: T__40
    	    {
    	        /* 1:10: T__40 */
    	        mT__40();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // T.g:1:16: T__41
    	    {
    	        /* 1:16: T__41 */
    	        mT__41();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // T.g:1:22: T__42
    	    {
    	        /* 1:22: T__42 */
    	        mT__42();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // T.g:1:28: T__43
    	    {
    	        /* 1:28: T__43 */
    	        mT__43();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // T.g:1:34: T__44
    	    {
    	        /* 1:34: T__44 */
    	        mT__44();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // T.g:1:40: T__45
    	    {
    	        /* 1:40: T__45 */
    	        mT__45();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // T.g:1:46: FuncDec
    	    {
    	        /* 1:46: FuncDec */
    	        mFuncDec();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // T.g:1:54: Equal
    	    {
    	        /* 1:54: Equal */
    	        mEqual();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // T.g:1:60: Minus
    	    {
    	        /* 1:60: Minus */
    	        mMinus();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // T.g:1:66: Dollar
    	    {
    	        /* 1:66: Dollar */
    	        mDollar();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // T.g:1:73: Assign
    	    {
    	        /* 1:73: Assign */
    	        mAssign();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // T.g:1:80: PlusAssign
    	    {
    	        /* 1:80: PlusAssign */
    	        mPlusAssign();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // T.g:1:91: MinusAssign
    	    {
    	        /* 1:91: MinusAssign */
    	        mMinusAssign();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // T.g:1:103: DoubleOpenSquareBracket
    	    {
    	        /* 1:103: DoubleOpenSquareBracket */
    	        mDoubleOpenSquareBracket();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // T.g:1:127: DoubleCloseSquareBracket
    	    {
    	        /* 1:127: DoubleCloseSquareBracket */
    	        mDoubleCloseSquareBracket();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // T.g:1:152: ShiftLeft
    	    {
    	        /* 1:152: ShiftLeft */
    	        mShiftLeft();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // T.g:1:162: ShiftRight
    	    {
    	        /* 1:162: ShiftRight */
    	        mShiftRight();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // T.g:1:173: VarName
    	    {
    	        /* 1:173: VarName */
    	        mVarName();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // T.g:1:181: ThenFunc
    	    {
    	        /* 1:181: ThenFunc */
    	        mThenFunc();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // T.g:1:190: Or
    	    {
    	        /* 1:190: Or */
    	        mOr();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // T.g:1:193: Gte
    	    {
    	        /* 1:193: Gte */
    	        mGte();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // T.g:1:197: Set
    	    {
    	        /* 1:197: Set */
    	        mSet();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // T.g:1:201: Silently
    	    {
    	        /* 1:201: Silently */
    	        mSilently();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // T.g:1:210: EndSilently
    	    {
    	        /* 1:210: EndSilently */
    	        mEndSilently();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // T.g:1:222: Choice
    	    {
    	        /* 1:222: Choice */
    	        mChoice();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // T.g:1:229: ChoiceLeft
    	    {
    	        /* 1:229: ChoiceLeft */
    	        mChoiceLeft();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // T.g:1:240: If
    	    {
    	        /* 1:240: If */
    	        mIf();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // T.g:1:243: ElseIf
    	    {
    	        /* 1:243: ElseIf */
    	        mElseIf();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // T.g:1:250: EndIf
    	    {
    	        /* 1:250: EndIf */
    	        mEndIf();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // T.g:1:256: Delay
    	    {
    	        /* 1:256: Delay */
    	        mDelay();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // T.g:1:262: AndAnd
    	    {
    	        /* 1:262: AndAnd */
    	        mAndAnd();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // T.g:1:269: OrOr
    	    {
    	        /* 1:269: OrOr */
    	        mOrOr();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // T.g:1:274: Time
    	    {
    	        /* 1:274: Time */
    	        mTime();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 34:
    	    // T.g:1:279: Int
    	    {
    	        /* 1:279: Int */
    	        mInt();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 35:
    	    // T.g:1:283: True
    	    {
    	        /* 1:283: True */
    	        mTrue();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 36:
    	    // T.g:1:288: False
    	    {
    	        /* 1:288: False */
    	        mFalse();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 37:
    	    // T.g:1:294: String
    	    {
    	        /* 1:294: String */
    	        mString();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 38:
    	    // T.g:1:301: Label
    	    {
    	        /* 1:301: Label */
    	        mLabel();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 39:
    	    // T.g:1:307: TEXT
    	    {
    	        /* 1:307: TEXT */
    	        mTEXT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 40:
    	    // T.g:1:312: COMMENT
    	    {
    	        /* 1:312: COMMENT */
    	        mCOMMENT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 41:
    	    // T.g:1:320: LINE_COMMENT
    	    {
    	        /* 1:320: LINE_COMMENT */
    	        mLINE_COMMENT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 42:
    	    // T.g:1:333: WS
    	    {
    	        /* 1:333: WS */
    	        mWS();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */

}


/* End of code
 * =============================================================================
 */
